### ISSUE TITLE
com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAuthIOException     at  request.execute()  in UsingDriveSDK.

### ISSUE THREAD

**Issue by iharshb** [anshuraj/VideoUploader#1]
`W/System.err: com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAuthIOException
W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:286)
W/System.err:     at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868)
W/System.err:     at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545)
W/System.err:     at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:562)
W/System.err:     at com.google.api.client.googleapis.media.MediaHttpUploader.executeUploadInitiation(MediaHttpUploader.java:519)
W/System.err:     at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:384)
W/System.err:     at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336)
W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:427)
W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
W/System.err:     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
W/System.err:     at me.anshuraj.videouploader.UsingDriveSDK$2.doInBackground(UsingDriveSDK.java:233)
W/System.err:     at me.anshuraj.videouploader.UsingDriveSDK$2.doInBackground(UsingDriveSDK.java:121)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
W/System.err: Caused by: com.google.android.gms.auth.GoogleAuthException: Unknown
W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.zza(Unknown Source)
W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:255)
W/System.err:     at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:279)
W/System.err: 	... 17 more`

**Comment by anshuraj** [comment]
How did you get this exception. Please provide full details.

**Comment by iharshb** [comment]
I got this when i changed mime type to image/*

    Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
        //Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType("image/*");
      
            startActivityForResult(intent,
                    FILE_SELECT_CODE);

     //In OnactivityResult
     case FILE_SELECT_CODE:
                if (resultCode == RESULT_OK) {
    //getting file path here and then uploading file
    upload(filePath);
    }
`Drive.Files.Insert request ;`
I got error at  `service.files().insert(fileMetadata, mediaContent).execute()`

**Error** : at above my post

**Comment by iharshb** [comment]
This is my onDoingBackground Method i changed only `InputStream` content mime type   and `setMimetype `to `image/*`

          `protected Void doInBackground(Void... params) {
                Log.d(TAG, " Inside upload thread ");
                try {
                    // Try to perform a Drive API request, for instance:
                    java.io.File mediaFile = new java.io.File(path);
                    InputStreamContent mediaContent =
                            new InputStreamContent("image/*",
                                    new BufferedInputStream(new FileInputStream(mediaFile)));
                    mediaContent.setLength(mediaFile.length());

                    File fileMetadata = new File();
                    fileMetadata.setTitle(mediaFile.getName());
                    fileMetadata.setMimeType("image/*");

                    Drive.Files.Insert request = null;

                    try {
                        request = service.files().insert(fileMetadata, mediaContent);
                        MediaHttpUploader uploader = request.getMediaHttpUploader();
                        uploader.setDirectUploadEnabled(false);
                        uploader.setChunkSize(MediaHttpUploader.MINIMUM_CHUNK_SIZE);
                        uploader.setProgressListener(new CustomProgressListener());
                        request.execute();

                    } catch (UserRecoverableAuthIOException e) {

                        Log.i(TAG, "User Recoverable Exception ");
                        error = 1;
                        startActivityForResult(e.getIntent(), COMPLETE_AUTHORIZATION_REQUEST_CODE);
                    }

                } catch (IOException e) {
                    Log.i("Err", "IOException");
                    error = 2;
                    e.printStackTrace();
                }
                return null;
            }`

**Comment by anshuraj** [comment]
Just to clear, this is not actually an issue.

Only changing content mime type and setMime type to image/* won't help, because in the showFileChooser()  type is set to video/*. The file chooser will return a video file link which you are trying to upload it as an image.

Again maybe the file manager you are trying to choose the file is returning relative file path rather than absolute file path.

**Comment by iharshb** [comment]
Solved. Not generated google console  OAuth consents.  :D
